PROJECT_ID = "my-project-id"
PROJECT_NUMBER = "XXXXXXXX"
REGION = "us-central1"
LOCATION = "US"
DEPLOYMENT_NAME = "copycat"
SERVICE_ACCOUNT = "copycat-sa"
USER_LIST = "myemail@somecompany.com,youremail@somecompany.com"